//MIT, 2016-present, WinterDev

 
using static Typography.TextBreak.Unicode13RangeInfoList;

namespace Typography.OpenFont
{


    public static class Unicode5_1Ranges
    {
        //from https://docs.microsoft.com/en-us/typography/opentype/spec/os2#ulunicoderange1-bits-031ulunicoderange2-bits-3263ulunicoderange3-bits-6495ulunicoderange4-bits-96127     
        //All available bits were exhausted as of Unicode 5.1. 
        //The bit assignments were last updated for OS/2 version 4 in OpenType 1.5. 
        //There are many additional ranges supported in the current version of Unicode that are not supported by these fields in the OS/2 table.
        //See the 'dlng' and 'slng' tags in the 'meta' table for an alternate mechanism to declare what scripts or languages that a font can support or 
        //is designed for. 

        //static UnicodeRangeInfo _(int startAt, int endAt, string name) => new UnicodeRangeInfo(startAt, endAt, name);

        //        //AUTOGEN
        //        public static readonly UnicodeRangeInfo
        //  Basic_Latin = _(0x0, 0x127, nameof(Basic_Latin)),
        //Latin_1_Supplement = _(0x128, 0x255, nameof(Latin_1_Supplement)),
        //Latin_Extended_A = _(0x256, 0x383, nameof(Latin_Extended_A)),
        //Latin_Extended_B = _(0x384, 0x591, nameof(Latin_Extended_B)),
        //IPA_Extensions = _(0x592, 0x687, nameof(IPA_Extensions)),
        //Phonetic_Extensions = _(0x7424, 0x7551, nameof(Phonetic_Extensions)),
        //Phonetic_Extensions_Supplement = _(0x7552, 0x7615, nameof(Phonetic_Extensions_Supplement)),
        //Spacing_Modifier_Letters = _(0x688, 0x767, nameof(Spacing_Modifier_Letters)),
        //Modifier_Tone_Letters = _(0x42752, 0x42783, nameof(Modifier_Tone_Letters)),
        //Combining_Diacritical_Marks = _(0x768, 0x879, nameof(Combining_Diacritical_Marks)),
        //Combining_Diacritical_Marks_Supplement = _(0x7616, 0x7679, nameof(Combining_Diacritical_Marks_Supplement)),
        //Greek_and_Coptic = _(0x880, 0x1023, nameof(Greek_and_Coptic)),
        //Coptic = _(0x11392, 0x11519, nameof(Coptic)),
        //Cyrillic = _(0x1024, 0x1279, nameof(Cyrillic)),
        //Cyrillic_Supplement = _(0x1280, 0x1327, nameof(Cyrillic_Supplement)),
        //Cyrillic_Extended_A = _(0x11744, 0x11775, nameof(Cyrillic_Extended_A)),
        //Cyrillic_Extended_B = _(0x42560, 0x42655, nameof(Cyrillic_Extended_B)),
        //Armenian = _(0x1328, 0x1423, nameof(Armenian)),
        //Hebrew = _(0x1424, 0x1535, nameof(Hebrew)),
        //Vai = _(0x42240, 0x42559, nameof(Vai)),
        //Arabic = _(0x1536, 0x1791, nameof(Arabic)),
        //Arabic_Supplement = _(0x1872, 0x1919, nameof(Arabic_Supplement)),
        //NKo = _(0x1984, 0x2047, nameof(NKo)),
        //Devanagari = _(0x2304, 0x2431, nameof(Devanagari)),
        //Bengali = _(0x2432, 0x2559, nameof(Bengali)),
        //Gurmukhi = _(0x2560, 0x2687, nameof(Gurmukhi)),
        //Gujarati = _(0x2688, 0x2815, nameof(Gujarati)),
        //Oriya = _(0x2816, 0x2943, nameof(Oriya)),
        //Tamil = _(0x2944, 0x3071, nameof(Tamil)),
        //Telugu = _(0x3072, 0x3199, nameof(Telugu)),
        //Kannada = _(0x3200, 0x3327, nameof(Kannada)),
        //Malayalam = _(0x3328, 0x3455, nameof(Malayalam)),
        //Thai = _(0x3584, 0x3711, nameof(Thai)),
        //Lao = _(0x3712, 0x3839, nameof(Lao)),
        //Georgian = _(0x4256, 0x4351, nameof(Georgian)),
        //Georgian_Supplement = _(0x11520, 0x11567, nameof(Georgian_Supplement)),
        //Balinese = _(0x6912, 0x7039, nameof(Balinese)),
        //Hangul_Jamo = _(0x4352, 0x4607, nameof(Hangul_Jamo)),
        //Latin_Extended_Additional = _(0x7680, 0x7935, nameof(Latin_Extended_Additional)),
        //Latin_Extended_C = _(0x11360, 0x11391, nameof(Latin_Extended_C)),
        //Latin_Extended_D = _(0x42784, 0x43007, nameof(Latin_Extended_D)),
        //Greek_Extended = _(0x7936, 0x8191, nameof(Greek_Extended)),
        //General_Punctuation = _(0x8192, 0x8303, nameof(General_Punctuation)),
        //Supplemental_Punctuation = _(0x11776, 0x11903, nameof(Supplemental_Punctuation)),
        //Superscripts_And_Subscripts = _(0x8304, 0x8351, nameof(Superscripts_And_Subscripts)),
        //Currency_Symbols = _(0x8352, 0x8399, nameof(Currency_Symbols)),
        //Combining_Diacritical_Marks_For_Symbols = _(0x8400, 0x8447, nameof(Combining_Diacritical_Marks_For_Symbols)),
        //Letterlike_Symbols = _(0x8448, 0x8527, nameof(Letterlike_Symbols)),
        //Number_Forms = _(0x8528, 0x8591, nameof(Number_Forms)),
        //Arrows = _(0x8592, 0x8703, nameof(Arrows)),
        //Supplemental_Arrows_A = _(0x10224, 0x10239, nameof(Supplemental_Arrows_A)),
        //Supplemental_Arrows_B = _(0x10496, 0x10623, nameof(Supplemental_Arrows_B)),
        //Miscellaneous_Symbols_and_Arrows = _(0x11008, 0x11263, nameof(Miscellaneous_Symbols_and_Arrows)),
        //Mathematical_Operators = _(0x8704, 0x8959, nameof(Mathematical_Operators)),
        //Supplemental_Mathematical_Operators = _(0x10752, 0x11007, nameof(Supplemental_Mathematical_Operators)),
        //Miscellaneous_Mathematical_Symbols_A = _(0x10176, 0x10223, nameof(Miscellaneous_Mathematical_Symbols_A)),
        //Miscellaneous_Mathematical_Symbols_B = _(0x10624, 0x10751, nameof(Miscellaneous_Mathematical_Symbols_B)),
        //Miscellaneous_Technical = _(0x8960, 0x9215, nameof(Miscellaneous_Technical)),
        //Control_Pictures = _(0x9216, 0x9279, nameof(Control_Pictures)),
        //Optical_Character_Recognition = _(0x9280, 0x9311, nameof(Optical_Character_Recognition)),
        //Enclosed_Alphanumerics = _(0x9312, 0x9471, nameof(Enclosed_Alphanumerics)),
        //Box_Drawing = _(0x9472, 0x9599, nameof(Box_Drawing)),
        //Block_Elements = _(0x9600, 0x9631, nameof(Block_Elements)),
        //Geometric_Shapes = _(0x9632, 0x9727, nameof(Geometric_Shapes)),
        //Miscellaneous_Symbols = _(0x9728, 0x9983, nameof(Miscellaneous_Symbols)),
        //Dingbats = _(0x9984, 0x10175, nameof(Dingbats)),
        //CJK_Symbols_And_Punctuation = _(0x12288, 0x12351, nameof(CJK_Symbols_And_Punctuation)),
        //Hiragana = _(0x12352, 0x12447, nameof(Hiragana)),
        //Katakana = _(0x12448, 0x12543, nameof(Katakana)),
        //Katakana_Phonetic_Extensions = _(0x12784, 0x12799, nameof(Katakana_Phonetic_Extensions)),
        //Bopomofo = _(0x12544, 0x12591, nameof(Bopomofo)),
        //Bopomofo_Extended = _(0x12704, 0x12735, nameof(Bopomofo_Extended)),
        //Hangul_Compatibility_Jamo = _(0x12592, 0x12687, nameof(Hangul_Compatibility_Jamo)),
        //Phags_pa = _(0x43072, 0x43135, nameof(Phags_pa)),
        //Enclosed_CJK_Letters_And_Months = _(0x12800, 0x13055, nameof(Enclosed_CJK_Letters_And_Months)),
        //CJK_Compatibility = _(0x13056, 0x13311, nameof(CJK_Compatibility)),
        //Hangul_Syllables = _(0x44032, 0x55215, nameof(Hangul_Syllables)),
        //Non_Plane_0 = _(0x65536, 0x1114111, nameof(Non_Plane_0)),
        //Phoenician = _(0x67840, 0x67871, nameof(Phoenician)),
        //CJK_Unified_Ideographs = _(0x19968, 0x40959, nameof(CJK_Unified_Ideographs)),
        //CJK_Radicals_Supplement = _(0x11904, 0x12031, nameof(CJK_Radicals_Supplement)),
        //Kangxi_Radicals = _(0x12032, 0x12255, nameof(Kangxi_Radicals)),
        //Ideographic_Description_Characters = _(0x12272, 0x12287, nameof(Ideographic_Description_Characters)),
        //CJK_Unified_Ideographs_Extension_A = _(0x13312, 0x19903, nameof(CJK_Unified_Ideographs_Extension_A)),
        //CJK_Unified_Ideographs_Extension_B = _(0x131072, 0x173791, nameof(CJK_Unified_Ideographs_Extension_B)),
        //Kanbun = _(0x12688, 0x12703, nameof(Kanbun)),
        //Private_Use_Area__plane_0_ = _(0x57344, 0x63743, nameof(Private_Use_Area__plane_0_)),
        //CJK_Strokes = _(0x12736, 0x12783, nameof(CJK_Strokes)),
        //CJK_Compatibility_Ideographs = _(0x63744, 0x64255, nameof(CJK_Compatibility_Ideographs)),
        //CJK_Compatibility_Ideographs_Supplement = _(0x194560, 0x195103, nameof(CJK_Compatibility_Ideographs_Supplement)),
        //Alphabetic_Presentation_Forms = _(0x64256, 0x64335, nameof(Alphabetic_Presentation_Forms)),
        //Arabic_Presentation_Forms_A = _(0x64336, 0x65023, nameof(Arabic_Presentation_Forms_A)),
        //Combining_Half_Marks = _(0x65056, 0x65071, nameof(Combining_Half_Marks)),
        //Vertical_Forms = _(0x65040, 0x65055, nameof(Vertical_Forms)),
        //CJK_Compatibility_Forms = _(0x65072, 0x65103, nameof(CJK_Compatibility_Forms)),
        //Small_Form_Variants = _(0x65104, 0x65135, nameof(Small_Form_Variants)),
        //Arabic_Presentation_Forms_B = _(0x65136, 0x65279, nameof(Arabic_Presentation_Forms_B)),
        //Halfwidth_And_Fullwidth_Forms = _(0x65280, 0x65519, nameof(Halfwidth_And_Fullwidth_Forms)),
        //Specials = _(0x65520, 0x65535, nameof(Specials)),
        //Tibetan = _(0x3840, 0x4095, nameof(Tibetan)),
        //Syriac = _(0x1792, 0x1871, nameof(Syriac)),
        //Thaana = _(0x1920, 0x1983, nameof(Thaana)),
        //Sinhala = _(0x3456, 0x3583, nameof(Sinhala)),
        //Myanmar = _(0x4096, 0x4255, nameof(Myanmar)),
        //Ethiopic = _(0x4608, 0x4991, nameof(Ethiopic)),
        //Ethiopic_Supplement = _(0x4992, 0x5023, nameof(Ethiopic_Supplement)),
        //Ethiopic_Extended = _(0x11648, 0x11743, nameof(Ethiopic_Extended)),
        //Cherokee = _(0x5024, 0x5119, nameof(Cherokee)),
        //Unified_Canadian_Aboriginal_Syllabics = _(0x5120, 0x5759, nameof(Unified_Canadian_Aboriginal_Syllabics)),
        //Ogham = _(0x5760, 0x5791, nameof(Ogham)),
        //Runic = _(0x5792, 0x5887, nameof(Runic)),
        //Khmer = _(0x6016, 0x6143, nameof(Khmer)),
        //Khmer_Symbols = _(0x6624, 0x6655, nameof(Khmer_Symbols)),
        //Mongolian = _(0x6144, 0x6319, nameof(Mongolian)),
        //Braille_Patterns = _(0x10240, 0x10495, nameof(Braille_Patterns)),
        //Yi_Syllables = _(0x40960, 0x42127, nameof(Yi_Syllables)),
        //Yi_Radicals = _(0x42128, 0x42191, nameof(Yi_Radicals)),
        //Tagalog = _(0x5888, 0x5919, nameof(Tagalog)),
        //Hanunoo = _(0x5920, 0x5951, nameof(Hanunoo)),
        //Buhid = _(0x5952, 0x5983, nameof(Buhid)),
        //Tagbanwa = _(0x5984, 0x6015, nameof(Tagbanwa)),
        //Old_Italic = _(0x66304, 0x66351, nameof(Old_Italic)),
        //Gothic = _(0x66352, 0x66383, nameof(Gothic)),
        //Deseret = _(0x66560, 0x66639, nameof(Deseret)),
        //Byzantine_Musical_Symbols = _(0x118784, 0x119039, nameof(Byzantine_Musical_Symbols)),
        //Musical_Symbols = _(0x119040, 0x119295, nameof(Musical_Symbols)),
        //Ancient_Greek_Musical_Notation = _(0x119296, 0x119375, nameof(Ancient_Greek_Musical_Notation)),
        //Mathematical_Alphanumeric_Symbols = _(0x119808, 0x120831, nameof(Mathematical_Alphanumeric_Symbols)),
        //Private_Use__plane_15_ = _(0x983040, 0x1048573, nameof(Private_Use__plane_15_)),
        //Private_Use__plane_16_ = _(0x1048576, 0x1114109, nameof(Private_Use__plane_16_)),
        //Variation_Selectors = _(0x65024, 0x65039, nameof(Variation_Selectors)),
        //Variation_Selectors_Supplement = _(0x917760, 0x917999, nameof(Variation_Selectors_Supplement)),
        //Tags = _(0x917504, 0x917631, nameof(Tags)),
        //Limbu = _(0x6400, 0x6479, nameof(Limbu)),
        //Tai_Le = _(0x6480, 0x6527, nameof(Tai_Le)),
        //New_Tai_Lue = _(0x6528, 0x6623, nameof(New_Tai_Lue)),
        //Buginese = _(0x6656, 0x6687, nameof(Buginese)),
        //Glagolitic = _(0x11264, 0x11359, nameof(Glagolitic)),
        //Tifinagh = _(0x11568, 0x11647, nameof(Tifinagh)),
        //Yijing_Hexagram_Symbols = _(0x19904, 0x19967, nameof(Yijing_Hexagram_Symbols)),
        //Syloti_Nagri = _(0x43008, 0x43055, nameof(Syloti_Nagri)),
        //Linear_B_Syllabary = _(0x65536, 0x65663, nameof(Linear_B_Syllabary)),
        //Linear_B_Ideograms = _(0x65664, 0x65791, nameof(Linear_B_Ideograms)),
        //Aegean_Numbers = _(0x65792, 0x65855, nameof(Aegean_Numbers)),
        //Ancient_Greek_Numbers = _(0x65856, 0x65935, nameof(Ancient_Greek_Numbers)),
        //Ugaritic = _(0x66432, 0x66463, nameof(Ugaritic)),
        //Old_Persian = _(0x66464, 0x66527, nameof(Old_Persian)),
        //Shavian = _(0x66640, 0x66687, nameof(Shavian)),
        //Osmanya = _(0x66688, 0x66735, nameof(Osmanya)),
        //Cypriot_Syllabary = _(0x67584, 0x67647, nameof(Cypriot_Syllabary)),
        //Kharoshthi = _(0x68096, 0x68191, nameof(Kharoshthi)),
        //Tai_Xuan_Jing_Symbols = _(0x119552, 0x119647, nameof(Tai_Xuan_Jing_Symbols)),
        //Cuneiform = _(0x73728, 0x74751, nameof(Cuneiform)),
        //Cuneiform_Numbers_and_Punctuation = _(0x74752, 0x74879, nameof(Cuneiform_Numbers_and_Punctuation)),
        //Counting_Rod_Numerals = _(0x119648, 0x119679, nameof(Counting_Rod_Numerals)),
        //Sundanese = _(0x7040, 0x7103, nameof(Sundanese)),
        //Lepcha = _(0x7168, 0x7247, nameof(Lepcha)),
        //Ol_Chiki = _(0x7248, 0x7295, nameof(Ol_Chiki)),
        //Saurashtra = _(0x43136, 0x43231, nameof(Saurashtra)),
        //Kayah_Li = _(0x43264, 0x43311, nameof(Kayah_Li)),
        //Rejang = _(0x43312, 0x43359, nameof(Rejang)),
        //Cham = _(0x43520, 0x43615, nameof(Cham)),
        //Ancient_Symbols = _(0x65936, 0x65999, nameof(Ancient_Symbols)),
        //Phaistos_Disc = _(0x66000, 0x66047, nameof(Phaistos_Disc)),
        //Carian = _(0x66208, 0x66271, nameof(Carian)),
        //Lycian = _(0x66176, 0x66207, nameof(Lycian)),
        //Lydian = _(0x67872, 0x67903, nameof(Lydian)),
        //Domino_Tiles = _(0x127024, 0x127135, nameof(Domino_Tiles)),
        //Mahjong_Tiles = _(0x126976, 0x127023, nameof(Mahjong_Tiles))
        //            ;


        //        //---------
        //        //AUTOGEN
        //        static readonly UnicodeRangeInfo[] s_langRangs = new UnicodeRangeInfo[]
        //        {
        //                Basic_Latin,
        //Latin_1_Supplement,
        //Latin_Extended_A,
        //Latin_Extended_B,
        //IPA_Extensions,
        //Phonetic_Extensions,
        //Phonetic_Extensions_Supplement,
        //Spacing_Modifier_Letters,
        //Modifier_Tone_Letters,
        //Combining_Diacritical_Marks,
        //Combining_Diacritical_Marks_Supplement,
        //Greek_and_Coptic,
        //Coptic,
        //Cyrillic,
        //Cyrillic_Supplement,
        //Cyrillic_Extended_A,
        //Cyrillic_Extended_B,
        //Armenian,
        //Hebrew,
        //Vai,
        //Arabic,
        //Arabic_Supplement,
        //NKo,
        //Devanagari,
        //Bengali,
        //Gurmukhi,
        //Gujarati,
        //Oriya,
        //Tamil,
        //Telugu,
        //Kannada,
        //Malayalam,
        //Thai,
        //Lao,
        //Georgian,
        //Georgian_Supplement,
        //Balinese,
        //Hangul_Jamo,
        //Latin_Extended_Additional,
        //Latin_Extended_C,
        //Latin_Extended_D,
        //Greek_Extended,
        //General_Punctuation,
        //Supplemental_Punctuation,
        //Superscripts_And_Subscripts,
        //Currency_Symbols,
        //Combining_Diacritical_Marks_For_Symbols,
        //Letterlike_Symbols,
        //Number_Forms,
        //Arrows,
        //Supplemental_Arrows_A,
        //Supplemental_Arrows_B,
        //Miscellaneous_Symbols_and_Arrows,
        //Mathematical_Operators,
        //Supplemental_Mathematical_Operators,
        //Miscellaneous_Mathematical_Symbols_A,
        //Miscellaneous_Mathematical_Symbols_B,
        //Miscellaneous_Technical,
        //Control_Pictures,
        //Optical_Character_Recognition,
        //Enclosed_Alphanumerics,
        //Box_Drawing,
        //Block_Elements,
        //Geometric_Shapes,
        //Miscellaneous_Symbols,
        //Dingbats,
        //CJK_Symbols_And_Punctuation,
        //Hiragana,
        //Katakana,
        //Katakana_Phonetic_Extensions,
        //Bopomofo,
        //Bopomofo_Extended,
        //Hangul_Compatibility_Jamo,
        //Phags_pa,
        //Enclosed_CJK_Letters_And_Months,
        //CJK_Compatibility,
        //Hangul_Syllables,
        //Non_Plane_0,//skip NOne_Plane_0 
        //Phoenician,
        //CJK_Unified_Ideographs,
        //CJK_Radicals_Supplement,
        //Kangxi_Radicals,
        //Ideographic_Description_Characters,
        //CJK_Unified_Ideographs_Extension_A,
        //CJK_Unified_Ideographs_Extension_B,
        //Kanbun,
        //Private_Use_Area__plane_0_,
        //CJK_Strokes,
        //CJK_Compatibility_Ideographs,
        //CJK_Compatibility_Ideographs_Supplement,
        //Alphabetic_Presentation_Forms,
        //Arabic_Presentation_Forms_A,
        //Combining_Half_Marks,
        //Vertical_Forms,
        //CJK_Compatibility_Forms,
        //Small_Form_Variants,
        //Arabic_Presentation_Forms_B,
        //Halfwidth_And_Fullwidth_Forms,
        //Specials,
        //Tibetan,
        //Syriac,
        //Thaana,
        //Sinhala,
        //Myanmar,
        //Ethiopic,
        //Ethiopic_Supplement,
        //Ethiopic_Extended,
        //Cherokee,
        //Unified_Canadian_Aboriginal_Syllabics,
        //Ogham,
        //Runic,
        //Khmer,
        //Khmer_Symbols,
        //Mongolian,
        //Braille_Patterns,
        //Yi_Syllables,
        //Yi_Radicals,
        //Tagalog,
        //Hanunoo,
        //Buhid,
        //Tagbanwa,
        //Old_Italic,
        //Gothic,
        //Deseret,
        //Byzantine_Musical_Symbols,
        //Musical_Symbols,
        //Ancient_Greek_Musical_Notation,
        //Mathematical_Alphanumeric_Symbols,
        //Private_Use__plane_15_,
        //Private_Use__plane_16_,
        //Variation_Selectors,
        //Variation_Selectors_Supplement,
        //Tags,
        //Limbu,
        //Tai_Le,
        //New_Tai_Lue,
        //Buginese,
        //Glagolitic,
        //Tifinagh,
        //Yijing_Hexagram_Symbols,
        //Syloti_Nagri,
        //Linear_B_Syllabary,
        //Linear_B_Ideograms,
        //Aegean_Numbers,
        //Ancient_Greek_Numbers,
        //Ugaritic,
        //Old_Persian,
        //Shavian,
        //Osmanya,
        //Cypriot_Syllabary,
        //Kharoshthi,
        //Tai_Xuan_Jing_Symbols,
        //Cuneiform,
        //Cuneiform_Numbers_and_Punctuation,
        //Counting_Rod_Numerals,
        //Sundanese,
        //Lepcha,
        //Ol_Chiki,
        //Saurashtra,
        //Kayah_Li,
        //Rejang,
        //Cham,
        //Ancient_Symbols,
        //Phaistos_Disc,
        //Carian,
        //Lycian,
        //Lydian,
        //Domino_Tiles,
        //Mahjong_Tiles,

        //        }; 
        ////-----------
        //public static IEnumerable<UnicodeRangeInfo> GetUnicodeLangRangeIter()
        //{
        //    for (int i = 0; i < s_langRangs.Length; ++i)
        //    {
        //        yield return s_langRangs[i];
        //    }
        //}

        public static BitposAndAssciatedUnicodeRanges GetUnicodeRanges(int bitpos)
        {
            return s_bitposAndAssocRanges[bitpos];
        }

        static readonly BitposAndAssciatedUnicodeRanges[] s_bitposAndAssocRanges = new BitposAndAssciatedUnicodeRanges[]
        {

            //AUTOGEN
_(0,  //0-127
           C0_controls,
           ASCII_punctuation_and_symbols_1,
           ASCII_digits,
           ASCII_punctuation_and_symbols_2,
           Uppercase_Latin_alphabet,
           ASCII_punctuation_and_symbols_3,
           Lowercase_Latin_alphabet,
           ASCII_punctuation_and_symbols_4,
           Control_character_2
           ),
_(1,//128-255
           C1_controls,
           Latin_1_punctuation_and_symbols,
           Vulgar_fractions,
           Punctuation_5,
           Letters_of_the_Latin_1_Supplement_part1,
           Mathematical_operator_multiplication,
           Letters_of_the_Latin_1_Supplement_part2,
           Mathematical_operator_division,
           Letters_of_Latin_1_Supplement_part3 ),
//
_(2,Latin_Extended_A),
_(3,Latin_Extended_B),

_(4,IPA_Extensions,Phonetic_Extensions /*, Unicode13RangeInfoList.Phonetic_Extensions_Supplement*/),
_(5,Spacing_Midifier_Letters,Modifier_Tone_Letters),

_(6,Combining_Diacritical_Marks,Combining_Diacritical_Marks_Supplement),
_(7,Greek_and_Coptic),
_(8,Coptic),
_(9,Cyrillic,Cyrillic_Supplement,Cyrillic_Extended_A,Cyrillic_Extended_B),
_(10,Armenian),
_(11,Hebrew),
_(12,Vai),
_(13,Arabic,Arabic_Supplement),
_(14,N_Ko),
_(15,Devanagari),
_(16,Bengali),
_(17,Gurmukhi),
_(18,Gujarati),
_(19,Oriya),
_(20,Tamil),
_(21,Telugu),
_(22,Kannada),
_(23,Malayalam),
_(24,Thai),
_(25,Lao),
_(26,Georgian,Georgian_Supplement),
_(27,Balinese),
_(28,Hangul_Jamo),
_(29,Latin_Extended_Additional,Latin_Extended_C,Latin_Extended_D),
_(30,Greek_Extended),
_(31,General_Punctuation,Supplemental_Punctuation),
_(32,Superscripts_and_Subscripts),
_(33,Currency_Symbols),
_(34,Combining_Diacritical_Marks_for_Symbols),
_(35,Letterlike_Symbols),
_(36,Number_Forms),
_(37,Arrows,Supplemental_Arrows_A,Supplemental_Arrows_B,Miscellaneous_Symbols_and_Arrows),
_(38,Mathematical_Operators,Supplemental_Mathematical_Operators,Miscellaneous_Mathematical_Symbols_A,Miscellaneous_Mathematical_Symbols_B),
_(39,Miscellaneous_Technical),
_(40,Control_Pictures),
_(41,Optical_Character_Recognition),
_(42,Enclosed_Alphanumerics),
_(43,Box_Drawing),
_(44,Block_Elements),
_(45,Geometric_Shapes),
_(46,Miscellaneous_Symbols),
_(47,Dingbat ),
_(48, CJK_Symbols_and_Punctuation ),
_(49,Hiragana),
_(50,Katakana,Katakana_Phonetic_Extensions),
_(51,Bopomofo,Bopomofo_Extended),
_(52,Hangul_Compatibility_Jamo),
_(53,Phags_pa),
_(54,Enclosed_CJK_Letters_and_Months),
_(55,CJK_Compatibility),
_(56,Hangul_Syllables),

//_(57,Non_Plane_0), //**TODO: review here again

_(58,Phoenician),
_(59,CJK_Unified_Ideographs,CJK_Radicals_Supplement,Kangxi_radical ,Ideographic_Description_Characters,CJK_Unified_Ideographs_Extension_A,CJK_Unified_Ideographs_Extension_B,Kanbun),
_(60,Private_Use_Area),/*Private_Use_Area__plane_0_*/
_(61,CJK_Strokes,CJK_Compatibility_Ideographs,CJK_Compatibility_Ideographs_Supplement),
_(62,Alphabetic_Presentation_Forms),
_(63,Arabic_Presentation_Forms_A),
_(64,Combining_Half_Marks),
_(65,Vertical_Forms,CJK_Compatibility_Forms),
_(66,Small_Form_Variants),
_(67,Arabic_Presentation_Forms_B),
_(68,Halfwidth_and_Fullwidth_Forms), //Halfwidth_And_Fullwidth_Forms
_(69,Specials),
_(70,Tibetan),
_(71,Syriac),
_(72,Thaana),
_(73,Sinhala),
_(74,Myanmar),
_(75,Ethiopic,Ethiopic_Supplement,Ethiopic_Extended),
_(76,Cherokee),
_(77,Unified_Canadian_Aboriginal_Syllabics),
_(78,Ogham),
_(79,Runic),
_(80,Khmer,Khmer_Symbols),
_(81,Mongolian),
_(82,Braille_Patterns),
_(83,Yi_Syllables,Yi_Radicals),
_(84,Tagalog,Hanunoo,Buhid,Tagbanwa),
_(85,Old_Italic),
_(86,Gothic),
_(87,Deseret),
_(88,Byzantine_Musical_Symbols,Musical_Symbols,Ancient_Greek_Musical_Notation),
_(89,Mathematical_Alphanumeric_Symbols),
_(90,Private_Use_Area),/* Private_Use__plane_15_,Private_Use__plane_16_),*/
_(91,Variation_Selectors,Variation_Selectors_Supplement),
_(92,Tags),
_(93,Limbu),
_(94,Tai_Le),
_(95,New_Tai_Lue),
_(96,Buginese),
_(97,Glagolitic),
_(98,Tifinagh),
_(99,Yijing_Hexagram_Symbols),
_(100,Syloti_Nagri),
_(101,Linear_B_Syllabary,Linear_B_Ideograms,Aegean_Numbers),
_(102,Ancient_Greek_Numbers),
_(103,Ugaritic),
_(104,Old_Persian),
_(105,Shavian),
_(106,Osmanya),
_(107,Cypriot_Syllabary),
_(108,Kharoshthi),
_(109,Tai_Xuan_Jing_Symbols),
_(110,Cuneiform,Cuneiform_Numbers_and_Punctuation),
_(111,Counting_Rod_Numerals),
_(112,Sundanese),
_(113,Lepcha),
_(114,Ol_Chiki),
_(115,Saurashtra),
_(116,Kayah_Li),
_(117,Rejang),
_(118,Cham),
_(119,Ancient_Symbols),
_(120,Phaistos_Disc),
_(121,Carian,Lycian,Lydian),
_(122,Domino_Tiles,Mahjong_Tiles),

        };

        static BitposAndAssciatedUnicodeRanges _(int bitpos, params UnicodeRangeInfo[] ranges) => new BitposAndAssciatedUnicodeRanges(bitpos, ranges);

        public const int MAX_BITPOS = 122;



    }
}